### ISSUE TITLE
Acpype -I gives error `ACPYPE FAILED: Only ONE Residue is allowed for ACPYPE to work`

### ISSUE THREAD

**Issue by gundalav** [alanwilter/acpype#65]
I have the was trying a ligand pub file with `acpype`
It's downloadable **[here](https://justpaste.it/3ec7u)**.

But I get the following error

```
 $ acpype -i my_ligand.pdb
============================================================================
| ACPYPE: AnteChamber PYthon Parser interfacE v. 2021.12.14 (c) 2021 AWSdS |
============================================================================
ERROR: more than one residue detected '{'PRO', 'GLN', 'LYS', 'TYR', 'THR', 'HIS', 'GLU', 'ASN', 'SER', 'CYS', 'ASP', 'GLY', 'PHE', 'MET', 'VAL', 'ALA', 'ARG'}'
ERROR: verify your input file 'my_ligand.pdb'. Aborting ...
ACPYPE FAILED: Only ONE Residue is allowed for ACPYPE to work
Total time of execution: less than a second
```

How can I resolve it?

-GV

**Comment by alanwilter** [comment]
Sorry, the answer is very clear, you gave a PDB with many residues, it won't work, you need a pdb with only one residue, the one you want the topology. Read [here](https://github.com/alanwilter/acpype/wiki/Tutorial-Using-ACPYPE-for-GROMACS) for an example. Though it's not updated yet, it shows what you have to do.

**Comment by gundalav** [comment]
Hi,

I found your website Tutorial Using ACPYPE for GROMACS
<https://github.com/alanwilter/acpype/wiki/Tutorial-Using-ACPYPE-for-GROMACS>
extremely
useful.
Much more straightforward than the GROMACS tutorial.

Would you please kindly add how to calculate the* interaction energy *
following
GROMACS initial tutorial here
<http://www.mdtutorials.com/gmx/complex/09_analysis.html>?

We'd like to get interaction_energy.xvg file for final plotting.

Lastly, in your Run minimization and short simulation step you use
gmx_d. Should it be gmx instead?

Sincerely,
G.V.

**Comment by alanwilter** [comment]
Thanks for the observations. This tutorial still need to be updated. I probably used `gmx_d` for double precision or multi-cpus, I don't remember the detail anymore. I'll try to do a first round of update asap.

I do intend to add more tutorial and certainly I intend to address protein-ligand interactions energy but I don't know when I'll find time.

Also, I do like Justin's tutorials because they are really rich in details. Don't get me wrong but we try to put in few pages many years of experience and, though it may look "simpler" now, the devil's always in the details.
